# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConnectAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConnectAPI

    pod 'RxSwift', '6.0.0'
    pod 'RxCocoa', '6.0.0'

  target 'ConnectAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConnectAPIUITests' do
    # Pods for testing
  end

end
